/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author rodri
 */
public class budgetFrame extends javax.swing.JFrame {

    /**
     * Creates new form budgetFrame
     */
    public budgetFrame() {
        this.setUndecorated(true);
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelBalanceText = new javax.swing.JLabel();
        jTextFieldActualBalance = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelImageTop = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonTakeBalance = new javax.swing.JButton();
        jButtonDeposit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Sign Out");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 120, -1));

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_JD-18_2252388.png"))); // NOI18N
        jPanel1.add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 116));

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("someone@someone.com");
        jPanel1.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 182, 27));

        jLabelWelcome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWelcome.setText("Welcome,");
        jPanel1.add(jLabelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabelUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserName.setText("Someone");
        jPanel1.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 100, -1));

        jLabelBalanceText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelBalanceText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBalanceText.setText("My Balance:");
        jPanel1.add(jLabelBalanceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jTextFieldActualBalance.setEditable(false);
        jTextFieldActualBalance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldActualBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActualBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldActualBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("$");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 30, 50));

        jLabelImageTop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelImageTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/wood-2065366_1920.jpg"))); // NOI18N
        jPanel1.add(jLabelImageTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 170));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTakeBalance.setText("Take from Balance");
        jPanel2.add(jButtonTakeBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 140, 50));

        jButtonDeposit.setText("Make a Deposit");
        jPanel2.add(jButtonDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/money-2724235_640.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldActualBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActualBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActualBalanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(budgetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(budgetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(budgetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(budgetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new budgetFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDeposit;
    private javax.swing.JButton jButtonTakeBalance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBalanceText;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelImageTop;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldActualBalance;
    // End of variables declaration//GEN-END:variables
}
